[versions]
#General/Shared Versions
slf4j-api= { strictly = "2.0.17" }
logback = "1.5.34" 
antlr4 = "4.13.2"

opentelemetry = "1.63.0"
opentelemetry-java = "2.29.0"
opentelemetry-java-logging = "2.29.0-alpha"

# Lookup and Service Annotations
org-netbeans = "RELEASE280"

# Testing
junit = "6.0.2"
junit-launcher = "6.0.2"

[libraries]
org-slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
ch-qos-logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

org-antlr-antlr4 = { module = "org.antlr:antlr4", version.ref="antlr4" }
org-antlr-antlr4-runtime = { module = "org.antlr:antlr4-runtime", version.ref="antlr4" }

io-opentelemetry-instrumentation-logback-mdc = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-mdc-1.0", version.ref = "opentelemetry-java-logging" }
io-opentelemetry-api = { module="io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry" }
io-opentelemetry-sdk = { module="io.opentelemetry:opentelemetry-sdk", version.ref = "opentelemetry" }
io-opentelemetry-exporter-logging = { module="io.opentelemetry:opentelemetry-exporter-logging", version.ref="opentelemetry" }
io-opentelemetry-instrumentation-java = { module="io.opentelemetry.instrumentation:opentelemetry-instrumentation-api", version.ref = "opentelemetry-java" }

org-netbeans-lookup = { module = "org.netbeans.api:org-openide-util-lookup", version.ref = "org-netbeans" }

# test deps
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-launcher" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junit-launcher" }
junit-platform-commons = { module = "org.junit.platform:junit-platform-commons", version.ref = "junit-launcher" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params" }
slf4j-jdk14 = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4j-api"}

org-slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j-api" }

[bundles]
junit = [ "junit-api", "junit-engine", "junit-params" ]
junit-platform = [ "junit-platform-launcher", "junit-platform-engine", "junit-platform-commons" ]
